export default function ImportCard({
    logo,
    alt,
    title,
    subtitle,
    buttonText,
    onButtonClick,
}) {
    return (
        <div
            className="
                group
                w-105
                rounded-3xl
                bg-zinc-900/80
                p-10
                flex
                flex-col
                items-center
                gap-8
                transition-all
                duration-300
                hover:bg-zinc-800
                hover:-translate-y-1
                shadow-lg
                hover:shadow-2xl
            "
        >
            <img
                src={logo}
                alt={alt}
                className="
                    h-20
                    object-contain
                "
            />

            <p
                className="
                    text-zinc-300
                    text-3xl
                    font-light
                    text-center
                "
            >
                {subtitle}
            </p>

            <button
                onClick={onButtonClick}
                className="
                    px-12
                    py-3
                    rounded-2xl
                    bg-blue-500
                    text-white
                    text-2xl
                    font-medium
                    transition
                    hover:bg-blue-400
                    active:scale-95
                "
            >
                {buttonText}
            </button>
        </div>
    );
}